"""Added favicon_url column to PasswordEntry model

Revision ID: 5285b2ca6a78
Revises: 33f309e41329
Create Date: 2024-10-17 15:36:51.968668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5285b2ca6a78'
down_revision = '33f309e41329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favicon_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_entries', schema=None) as batch_op:
        batch_op.drop_column('favicon_url')

    # ### end Alembic commands ###
